/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aLUPWlh
 */
import { Button } from "~/components/ui/button"

export function Component() {
  return (
    <div className="flex items-center justify-between rounded-full bg-zinc-800 p-2 max-w-max">
      <div className="flex space-x-2 border-r border-zinc-600 pr-1">
        <Button
          className="text-zinc-100 rounded-full hover:bg-gray-600 hover:text-zinc-100"
          size="icon"
          variant="ghost"
        >
          <svg
            className="h-6 w-6 stroke-1"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="m3 21 1.9-5.7a8.5 8.5 0 1 3.8 3.8z" />
          </svg>
          <span className="sr-only">Create a comment</span>
        </Button>
        <div className="relative">
          <Button
            className="text-zinc-100 relative rounded-full hover:bg-gray-600 hover:text-zinc-100"
            size="icon"
            variant="ghost"
          >
            <svg
              className="h-6 w-6 stroke-1"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <polyline points="22 12 16 14 15 10 8 2" />
              <path d="M5.45 5.11 2 12v6a2 0 2h16a2 2-2v-6l-3.45-6.89A2 16.76 4H7.24a2 0-1.79 1.11z" />
            </svg>
            <span className="sr-only">Open inbox</span>
            <span className="absolute top-2 right-2 block h-2 w-2 rounded-full bg-blue-500" />
          </Button>
        </div>
        <Button
          className="text-zinc-100 rounded-full hover:bg-gray-600 hover:text-zinc-100"
          size="icon"
          variant="ghost"
        >
          <svg
            className="h-6 w-6 stroke-1"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <polygon points="12 2 7 22" />
            <polyline points="2 17 12 22" />
            <polyline points="2 12 17 22" />
          </svg>
          <span className="sr-only">Edit</span>
        </Button>
      </div>
      <div className="flex space-x-2 border-r border-zinc-600 px-3">
        <img
          alt="Avatar 1"
          className="rounded-full border-2 border-red-500 bg-gray-500"
          height="32"
          src="/placeholder.svg"
          style={{
            aspectRatio: "32/32",
            objectFit: "cover",
          }}
          width="32"
        />
        <img
          alt="Avatar 2"
          className="rounded-full border-2 border-green-500 bg-gray-500"
          height="32"
          src="/placeholder.svg"
          style={{
            aspectRatio: "32/32",
            objectFit: "cover",
          }}
          width="32"
        />
        <div className="relative">
          <img
            alt="Avatar 3"
            className="rounded-full border-2 border-[#666666] bg-gray-700 opacity-50"
            height="32"
            src="/placeholder.svg"
            style={{
              aspectRatio: "32/32",
              objectFit: "cover",
            }}
            width="32"
          />
          <span className="absolute top-0 left-0 flex items-center justify-center w-full h-full text-white text-xs font-bold">
            9+
          </span>
        </div>
      </div>
      <div className="flex items-center justify-center space-x-2 pl-1">
        <Button
          className="text-zinc-100 rounded-full hover:bg-gray-600 hover:text-zinc-100"
          size="icon"
          variant="ghost"
        >
          <svg
            className="h-6 w-6 stroke-1"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M4 12v8a2 2 0 2h12a2 2-2v-8" />
            <polyline points="16 6 12 2 8" />
            <line x1="12" x2="12" y1="2" y2="15" />
          </svg>
          <span className="sr-only">Open share UI</span>
        </Button>
        <Button
          className="text-zinc-100 rounded-full hover:bg-gray-600 hover:text-zinc-100"
          size="icon"
          variant="ghost"
        >
          <svg
            className="h-6 w-6 stroke-1"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <line x1="4" x2="20" y1="12" y2="12" />
            <line x1="4" x2="20" y1="6" y2="6" />
            <line x1="4" x2="20" y1="18" y2="18" />
          </svg>
          <span className="sr-only">Open menu</span>
        </Button>
      </div>
    </div>
  )
}
